version: "3.8"
services:
  backend:
    build: ./server
    ports:
      - "3000:3000"
    volumes: 
      - ./server:/app
    command: npm start

  frontend:
    build: ./client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
    command: npm run dev
