# Use Node image
FROM node:18

# Set working directory
WORKDIR /app

# Copy package.json and install
COPY package*.json ./
RUN npm install

# Copy the rest
COPY . .

# Expose port (e.g., 5000 for Express)
EXPOSE 5000

# Start the server
CMD ["node", "index.js"]
# CMD ["npm", "run", "dev"]
# CMD ['npm','start'] 